#ifndef TESTOWANIE_GITA_MENU_H
#define TESTOWANIE_GITA_MENU_H
void menu();
void insertingNumbers();
void sum();
void subtraction();
void multiplication();
void division();
#endif //TESTOWANIE_GITA_MENU_H
